export default function Privacy() {
  return <main>
    <p className="eyebrow"><a href="/">CAVE CALS</a></p>
    <h1>Privacy Policy</h1>
    <p><strong>Effective date: October 8, 2026</strong></p>
    <p>Claim727 LLC ("Claim727," "we," "us," or "our") operates Cave Cals, a food and calorie tracking app. This policy explains what information Cave Cals processes, why we process it, when it is shared, and the choices available to you.</p>
    <h2>Information stored on your devices and iCloud</h2>
    <p>Your profile, calorie and macro goals, food diary and macros, saved foods, saved meals, and widget data are stored on your device and, when iCloud is enabled, in your private iCloud account using Apple CloudKit. We do not receive your iCloud credentials or control Apple's storage and security practices.</p>
    <h2>Calorie plans and weigh-ins</h2>
    <p>The optional calorie-plan setup uses the age, gender/reference selection, height, weight, activity, goal weight, and pace you enter to calculate a starting calorie estimate on your device. Saved plan answers and weigh-ins are kept in a protected local file excluded from device backups; they do not sync through our CloudKit diary or go to our backend, AI providers, or advertising services. Only the calorie goal you accept follows the diary and iCloud storage described above. The clinician-led-plan selection is temporary and is not saved as a diagnosis. Unfinished setup answers are discarded when the app exits.</p>
    <h2>Apple Health</h2>
    <p>Weight tracking and Apple Health sharing are optional, and each kind of sharing is off until you turn it on in the app and grant permission in Apple Health. With Weigh-ins sharing, Cave Cals writes your weigh-ins to Apple Health. With Calories &amp; macros sharing, Cave Cals writes, for each food you log from the day you turn it on, the food's name, date and time, calories, and, when known, protein, carbohydrates, fat, and fiber; edits and deletions in Cave Cals update or remove those Health records. Cave Cals does not read any data from Apple Health. Health data written by Cave Cals is created on your device by Apple's HealthKit; it is not sent to our backend, AI providers, or advertising services, and it is never used for advertising or sold. Other apps may access those records only under the permissions you give them in Apple Health. Turning sharing off pauses future exports; existing Health records remain there. You can manage Health permissions and records in Apple's controls.</p>
    <p>In You, Forget plan details removes saved plan answers while keeping your daily calorie goal and weigh-ins. You can edit or delete weigh-ins in the app. Deleting a weigh-in also queues removal of its Cave Cals-created Health copy; this needs sharing enabled and write access to complete. A pending deletion retains only the record identity and sync state, not the weight measurement.</p>
    <h2>Progress photos</h2>
    <p>Progress photos you take or choose are saved only in Cave Cals on your iPhone, with their angle label and date. They are re-saved without location or other photo metadata, protected by your device passcode, and included in your iPhone's own backups (iCloud Backup or a computer backup) so a restored iPhone keeps them. They do not sync through our CloudKit diary and are never sent to our backend, AI providers, or advertising services. Choosing a photo from your library uses Apple's photo picker, which shares only the photo you pick. A photo leaves the app only if you share it. Deleting a photo in the app removes it from your iPhone; copies already in earlier backups follow Apple's backup controls.</p>
    <h2>Information sent to our services</h2>
    <p>When you search for a food, your search term is sent through our backend to FatSecret for food and restaurant nutrition information. Scanned barcodes are sent directly to Open Food Facts. Our backend processes your IP address and stores a daily hash and request counters for search rate limits; it does not store your food-search text in the database. Your diary is not sent to either food provider. When you choose AI meal photo or voice logging, the selected photo, video, or audio recording is uploaded to our backend and sent to OpenAI to identify foods, transcribe audio, and estimate portions, calories, and macros. When you use Siri or Shortcuts to log a food that Cave Cals cannot match on your device from your own history or saved meals, the words you said are sent to our backend and OpenAI to identify the food and estimate calories, like a voice log. If you choose to type or paste a meal description in Voice Log instead of speaking, that text is sent the same way. When you request a macro estimate for a food, only that food’s name, portion and calorie amount are sent to our backend and OpenAI; your full diary is not sent. When you import a recipe, the public link, the recipe photos you choose (up to five pages), or the recipe text or picture you paste is sent to our backend and OpenAI so it can be converted into editable meal items. When you ask Cave Coach for insights on the Progress screen, a summary your iPhone computes is sent to our backend and OpenAI: day counts, average calories, typical eating times, average macros, and the names of foods that show up more on days at or over your calorie goal. Your diary entries themselves are not sent, and the insights are not stored on our servers. AI results are estimates; review and edit them before saving.</p>
    <p>Our services process an anonymous internal identifier, device verification credentials, Apple purchase identifiers, subscription status, usage counters (including successful AI scans and an aggregate regular food-log count capped at 100), request timestamps, and technical logs needed for security, quotas, troubleshooting, and purchase validation. We do not require an email address, password, or social account to use Cave Cals.</p>
    <h2>Anonymous usage statistics and error reports</h2>
    <p>Starting with version 1.0.5, Cave Cals sends anonymous usage statistics and error reports to our backend so we can see which features help and fix what breaks. They include daily counts (such as app opens, how many foods were logged and by which method, scans, searches, edits, and deletions), setup and feature choices (such as whether a calorie goal is set, tracking options, Cave Cals+ membership, and whether Apple Health sharing, reminders, iCloud, or a widget are on), paywall and setup steps reached, your answer to “Where did you find Cave Cals?” (including anything you type under Other) and any discount code you apply, answers to the in-app rating question, error codes and messages with the app location that reported them, the app and iOS version, device type and model, time zone, and an approximate country derived from the connection. When a food search finds nothing anywhere, the search text is included so we can add missing foods. The first report from an iPhone that already has diary entries includes daily counts of those earlier entries by logging method.</p>
    <p>These reports use a random identifier created on your iPhone that is not linked to your AI account, purchases, name, or contact details, and we do not use them for advertising or tracking. They never include your diary entries, food names you logged, calories, macros, weights, or Apple Health data. Error reports from our backend include only the error type and code, not request content. You can turn this off at any time in Settings → Usage stats → Share anonymous usage stats; anything not yet sent is discarded.</p>
    <h2>Discount codes</h2>
    <p>When you apply a discount code, the app sends the code to our backend to check it, and the code is saved on your iPhone so Cave Cals+ shows its prices. We count how many times each code is applied, and how many times each code’s page on cavecals.com is visited and its App Store button is tapped. These are daily totals per code, kept without IP addresses, cookies, or device identifiers, and the pages don’t use cookies. Like food search, code checks use a daily hash of your IP address only for rate limits. The App Store link on a code’s page includes a campaign name, so Apple’s App Analytics can report downloads from that page in aggregate.</p>
    <h2>Purchases and third parties</h2>
    <p>Apple processes payments and provides subscription transaction information. RevenueCat provides subscription offerings, paywall services, entitlement status, and purchase restoration; it receives an anonymous app identifier, purchase information, and paywall interactions. Vercel hosts our web and API services, Neon hosts service records, OpenAI processes selected AI media, food details for requested macro estimates, Cave Coach summaries, and the recipe links, photos, and text you import, FatSecret provides food and restaurant nutrition data, and Open Food Facts provides barcode product data. Each provider processes information under its own terms and privacy policy.</p>
    <h2>Retention and deletion</h2>
    <p>Usage statistics are kept as daily counts. Error reports and searches that found nothing are deleted after 180 days, and other usage events after about 13 months.</p>
    <p>We request deletion of uploaded media after processing. Temporary uploads, estimates, and upload records expire after 24 hours and scheduled cleanup normally removes them within 48 hours. Operational backups and logs may persist for a limited period for security and reliability. OpenAI, Apple, RevenueCat, Vercel, Neon, FatSecret, and Open Food Facts may retain information under their own policies.</p>
    <p>Because Cave Cals does not require an account, we cannot identify a diary stored only on your device or private iCloud account. You can delete that data from the app or Apple device/iCloud controls. To request deletion of information held by Claim727, email <a href="mailto:phil@claim727.com">phil@claim727.com</a> and include enough detail to locate your records. We will verify the request and respond within a reasonable period.</p>
    <h2>Choices and permissions</h2>
    <p>Camera and microphone access are requested only when you use those features. Apple Health permission is requested only when you turn on Health sharing. Notification permission is requested after you have logged food on a few days; Cave Cals uses it only for a local morning reminder when nothing is logged yet, scheduled on your device, and you can turn reminders off in Settings. You can deny or revoke permissions in iOS Settings. You can use manual food and calorie logging without sending media to AI. You can manage or cancel subscriptions through your Apple ID subscription settings.</p>
    <h2>Security</h2>
    <p>We use encrypted transport, signed Apple purchase verification, device attestation, access-controlled temporary storage, and limited retention. No method of transmission or storage is guaranteed to be completely secure.</p>
    <h2>Children</h2>
    <p>Cave Cals is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you believe a child has provided information, contact us so we can investigate and delete it where appropriate.</p>
    <h2>Changes and contact</h2>
    <p>We may update this policy as Cave Cals changes. We will post the current version and effective date at this URL. Questions, privacy requests, and support requests can be sent to <a href="mailto:phil@claim727.com">phil@claim727.com</a>.</p>
    <p><strong>Claim727 LLC</strong><br /><a href="mailto:phil@claim727.com">phil@claim727.com</a></p>
  </main>;
}
